name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Push
        env:
          DOCKER_HUB_REPO: react-portfolio
        run: |
          docker build -t $DOCKER_HUB_REPO .
          docker tag $DOCKER_HUB_REPO:latest ${{ secrets.DOCKER_USER }}/$DOCKER_HUB_REPO:latest
          docker push ${{ secrets.DOCKER_USER }}/$DOCKER_HUB_REPO

      - name: Docker pull & Run In EC2
        uses: appleboy/ssh-action@master
        env:
          DOCKER_HUB_REPO: react-portfolio
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: REPO_DOCKER_HUB
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USER }}/$DOCKER_HUB_REPO
            sudo docker stop backend
            sudo docker rm backend
            sudo docker run --detach --name backend -p 5000:5000 ${{ secrets.DOCKER_USER }}/$DOCKER_HUB_REPO
            
            
            
            
            
